"""Event bus and event definitions for reactive SDK logic."""

import threading
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, TypeVar

if TYPE_CHECKING:
    from collections.abc import Callable


@dataclass(frozen=True)
class GameEvent:
    """Base class for all game events generated by the Bridge."""


T = TypeVar("T", bound=GameEvent)


@dataclass(frozen=True)
class TickEvent(GameEvent):
    """Fired every game engine tick (approx. 600ms)."""

    tick: int


@dataclass(frozen=True)
class InventoryChanged(GameEvent):
    """Fired when an item container (Inventory, Bank, etc) is updated."""

    container_id: int


@dataclass(frozen=True)
class ChatMessageReceived(GameEvent):
    """Fired when a new public, private, or game message is received."""

    sender: str
    message: str
    type: str


class EventBus:
    """Central event hub for subscribing to game state changes.

    Thread-safe: emit() is called from the background EventConsumer thread,
    wait_for() blocks the main thread via threading.Event.
    """

    def __init__(self):
        self._subscribers: dict[type[GameEvent], list[Callable[[Any], Any]]] = {}
        self._waiters: dict[type[GameEvent], list[tuple[threading.Event, list]]] = {}
        self._lock = threading.Lock()

    def subscribe(self, event_type: type[T], callback: Callable[[T], Any]):
        """Register a callback to be executed when an event of event_type is emitted."""
        with self._lock:
            if event_type not in self._subscribers:
                self._subscribers[event_type] = []  # type: ignore
            self._subscribers[event_type].append(callback)  # type: ignore

    def on(self, event_type: type[T]):
        """Subscribe a function to a specific event type via decorator."""

        def decorator(func: Callable[[T], Any]):
            self.subscribe(event_type, func)
            return func

        return decorator

    def emit(self, event: GameEvent):
        """Broadcast an event to all subscribers and signal any waiting threads."""
        event_type = type(event)

        with self._lock:
            waiters = self._waiters.pop(event_type, [])

        for waiter_event, result_holder in waiters:
            result_holder[0] = event
            waiter_event.set()

        with self._lock:
            callbacks = list(self._subscribers.get(event_type, []))

        for callback in callbacks:
            callback(event)

    def wait_for(self, event_type: type[GameEvent], timeout: float | None = None) -> Any:
        """Block until the next occurrence of a specific event type."""
        waiter = threading.Event()
        result: list = [None]
        entry = (waiter, result)

        with self._lock:
            self._waiters.setdefault(event_type, []).append(entry)

        try:
            if not waiter.wait(timeout=timeout):
                raise TimeoutError
            return result[0]
        finally:
            with self._lock:
                waiters = self._waiters.get(event_type)
                if waiters and entry in waiters:
                    waiters.remove(entry)
