#!/usr/bin/env python3
"""Generate widget field constants from proto enum."""

from __future__ import annotations

import re
from pathlib import Path

from loguru import logger


def parse_widget_properties(pb2_stub_path: Path) -> list[str]:
    """Parse WidgetProperty enum member names from bridge_pb2.pyi."""
    content = pb2_stub_path.read_text()
    pattern = r"WIDGET_PROP_(\w+):\s*_WidgetProperty\.ValueType\s*#\s*(\d+)"
    props = []
    for match in re.finditer(pattern, content):
        name = match.group(1)
        value = int(match.group(2))
        if value == 0:
            continue
        props.append(name)
    return props


def _upper_snake_to_camel(name: str) -> str:
    """Convert UPPER_SNAKE_CASE to camelCase."""
    parts = name.lower().split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def _prop_to_getter(name: str) -> str:
    """Convert a proto enum name (without WIDGET_PROP_ prefix) to a Java getter name."""
    if name.startswith("ON_"):
        suffix = _upper_snake_to_camel(name[3:])
        return f"getOn{suffix[0].upper()}{suffix[1:]}Listener"
    if name.startswith("IS_"):
        suffix = _upper_snake_to_camel(name[3:])
        return f"is{suffix[0].upper()}{suffix[1:]}"
    camel = _upper_snake_to_camel(name)
    return f"get{camel[0].upper()}{camel[1:]}"


def _camel_to_snake(name: str) -> str:
    """Convert camelCase to snake_case."""
    name = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
    name = re.sub("([a-z0-9])([A-Z])", r"\1_\2", name)
    return name.lower()


def generate_widget_fields(props: list[str]) -> str:
    """Generate escape/constants/_widgetfields.py content."""
    getters = sorted(_prop_to_getter(p) for p in props)

    literal_members = ",\n".join(f'    "{g}"' for g in getters)

    attr_lines = []
    for g in getters:
        snake = _camel_to_snake(g)
        attr_lines.append(f'    {snake}: WidgetField = "{g}"')
    attrs = "\n".join(attr_lines)

    return f'''\
"""Widget field types derived from the WidgetProperty proto enum.

Auto-generated by scripts/widget_generator.py — do not edit manually.
Run 'make all' to regenerate.
"""

from typing import Literal

WidgetField = Literal[
{literal_members},
]


class _WidgetFields:
{attrs}


WidgetFields = _WidgetFields()
'''


def main() -> None:
    repo_root = Path(__file__).parent.parent
    pb2_stub_path = (
        repo_root / "escape" / "_proto" / "bridge" / "v1" / "bridge_pb2.pyi"
    )
    widget_output = repo_root / "escape" / "constants" / "_widgetfields.py"

    if not pb2_stub_path.exists():
        raise FileNotFoundError(
            f"Generated proto stub not found: {pb2_stub_path}\n"
            "Run 'buf generate' first to generate proto stubs."
        )

    props = parse_widget_properties(pb2_stub_path)
    logger.info(f"Found {len(props)} widget properties")
    widget_output.write_text(generate_widget_fields(props))
    logger.info(f"Generated {widget_output}")


if __name__ == "__main__":
    main()
